### ISSUE TITLE
scripts panel missing

### ISSUE THREAD

**Issue by rmbw51** [fsancho/Complex-Network-Analysis#1]
I don't see the scripts panel... missing?

**Comment by fsancho** [comment]
Sorry! In the new version for NetLogo 6.0 I removed the scripts panel because everybody used the scripts through the Command Center (using scripts.nls to write their own scripts as new commands), but I didn't update the Readme. Do you need it?, it is easy to add again...

**Comment by rmbw51** [comment]
ah. ok, no problem... will try... thanks
PS maybe better you update the readme and info ;-)

**Comment by fsancho** [comment]
Done! As soon as I have time, I will change the pictures... Thanks!
